spring:
  application:
    name: AccountService

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

config:
  message: "AccountService Update"
