spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

resilience4j:
  circuitbreaker:
    instances:
      accountServiceCB:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

server:
  port: 9002
