spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

resilience4j:
  circuitbreaker:
    instances:
      accountServiceCB: # Must match the name used in @CircuitBreaker(name = "accountServiceCB")
        failure-rate-threshold: 50 # Open the circuit if 50% or more calls fail
        minimum-number-of-calls: 5 # CB starts calculating failure rate only after at least 5 calls
        sliding-window-size: 10 # Consider the last 10 calls for failure rate calculation
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 30s # Stay in OPEN state for 30 seconds before moving to HALF_OPEN
        permitted-number-of-calls-in-half-open-state: 3 #  Allow 3 test calls in HALF_OPEN state
        automatic-transition-from-open-to-half-open-enabled: true # # Automatically move from OPEN to HALF_OPEN after 30 seconds
  retry:
    instances:
      accountServiceRetry:
        max-attempts: 3
        wait-duration: 2
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.RetryableException
          - java.net.SocketTimeoutException
          - java.net.ConnectException
        ignore-exceptions:
          - feign.FeignException$NotFound   # Checks for the NOT FOUND (HTTP Status Code 404) which comes from AccountService if acct no not available 
          - jakarta.validation.ValidationException
  timelimiter:
    instances:
      accountServiceTimeLimiter:
        timeout-duration: 3s
        cancel-running-future: true
      

server:
  port: 9002
